version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/server'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'npm'
    directory: '/web'
    schedule:
      interval: 'weekly'
